### ISSUE TITLE
RAM usage 

### ISSUE THREAD

**Issue by ShayanAbedi** [CodingGarden/faqs#1]
Why do you always have around 13 gb free RAM? I have MacBook Pro with 16gb of memory (and almost the same specs as yours) and I've never seen iStat shows anything less than 10 gb of free memory

**Comment by furkanalptokac** [comment]
Yeah I wonder that as well. Because even stock Macs (mine too) are using 4-5gb memory. CJ's Mac is using 2.5gb when working. If it can be optimized, I want to know how to do.
