### ISSUE TITLE
Inventory App - Create test databse using postgres container

### ISSUE THREAD

**Issue by hassanfarahani** [CodingGarden/faqs#13]
I have another question about Inventory App Youtube series (11 videos). In one of the video, you created a test database by going inside the postgres container; but you said this is just a temporary solution & you will update postgres container to create test database on start (you can see a TODO in the knexfile.js) but you did not implement this (probably we should do this in docker-compose file) . Would you please tell me how we can create a test database without going inside the postgres container?

**Comment by w3cj** [comment]
If you still have this question, please ask on the discord: https://coding.garden/discord/
