### ISSUE TITLE
What extension shows packages size in VSCode

### ISSUE THREAD

**Issue by MrAmericanMike** [CodingGarden/faqs#8]
Simple that.

And also, what's the idea behind using something that displays that information, like why are packages sizes relevant if there is even an answer for that, but I guess it's specific to each project.

**Comment by drillskibo** [comment]
I think it is [Bundle Size](https://marketplace.visualstudio.com/items?itemName=ambar.bundle-size) but they would have to confirm that.
Also I don't think they're using it anymore based on [this gist](https://gist.github.com/w3cj/520eb023dd3531d1b654794f65aa434b) and [this repo](https://github.com/CodingGarden/vscode-settings).

**Comment by w3cj** [comment]
I don't use this extension any more but it was called ["import cost"](https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost)
