### ISSUE TITLE
About using very less memory.

### ISSUE THREAD

**Issue by furkanalptokac** [CodingGarden/faqs#9]
Yeah I wonder that as well. Because even stock Macs (mine too) are using 4-5gb memory. CJ's Mac is using 2.5gb when working. If it can be optimized, I want to know how to do.

_Originally posted by @furkanalptokac in https://github.com/CodingGarden/faqs/issues/1#issuecomment-830849145_

**Comment by w3cj** [comment]
Sorry this response is so late, but for the most part, I try to only run the apps I'm actually using. This keeps the memory footprint down.
